FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:rhel_9_1.23 AS builder

WORKDIR /go/src/github.com/stolostron/clusterclaims-controller
COPY . .

RUN make -f Makefile.prow compile

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

ENV USER_UID=1001

# Add the binary
COPY --from=builder /go/src/github.com/stolostron/clusterclaims-controller/build/_output/manager-clusterclaims .
COPY --from=builder /go/src/github.com/stolostron/clusterclaims-controller/build/_output/manager-clusterpools-delete .

USER ${USER_UID}
