FROM registry.ci.openshift.org/open-cluster-management/builder:go1.16-linux AS builder

WORKDIR /go/src/github.com/open-cluster-management/clusterclaims-controller
COPY . .

RUN make -f Makefile.prow compile

FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

ENV USER_UID=1001

# Add the binary
COPY --from=builder /go/src/github.com/open-cluster-management/clusterclaims-controller/build/_output/manager-clusterclaims .
COPY --from=builder /go/src/github.com/open-cluster-management/clusterclaims-controller/build/_output/manager-clusterpools-delete .

USER ${USER_UID}